applicationName: script-api

phase: LOCAL

active_voice:
  auth_token: auth token

open_ai:
  token: token
  model: gpt-4o
  temperature: 0.5

mysql:
  db_url: db
  pool_recycle: 3600

security:
  secret_key: secret key
  algorithm: HS256
  expires_delta: 1440

aws:
  region: region
  bucket: bucket
  access_key: access key
  secret_key: secret key

external_volume:
  path: "."

preprocessing:
  video_split_output_path: "./script"
  encoding_video_output: "./encoding"